# Generated by Django 2.1.3 on 2018-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventdepartment',
            name='event_dep_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
