# Generated by Django 2.1.1 on 2019-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_auto_20190112_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
