# Generated by Django 2.1.3 on 2018-11-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_auto_20181119_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='link_to',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
