# Generated by Django 2.1.1 on 2019-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_auto_20190112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
