# Generated by Django 2.1.3 on 2018-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_auto_20181119_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='objective',
            field=models.CharField(default='NA', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='round1',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='round2',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
    ]
