# Generated by Django 2.1.3 on 2018-11-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_auto_20181119_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorMaster',
            fields=[
                ('sponsor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=30)),
                ('sponsor_logo', models.CharField(max_length=200)),
                ('sponsor_info', models.CharField(default='No Info. Available', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sponsorcategory',
            name='sponsor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.SponsorMaster'),
        ),
    ]
