# Generated by Django 2.1.1 on 2019-01-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0007_auto_20190112_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='objective',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='round1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='round2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rules',
            field=models.CharField(max_length=1000),
        ),
    ]
