# Generated by Django 2.1.3 on 2018-11-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0007_auto_20181119_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='sponsorcategory',
            name='sponsor_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SponsorCategory',
        ),
    ]
