# Generated by Django 2.1.1 on 2018-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0008_auto_20181119_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.EmailField(max_length=254)),
                ('user_message', models.CharField(max_length=300)),
            ],
        ),
    ]
