# Generated by Django 2.1.1 on 2019-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0008_auto_20190112_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
