# Generated by Django 2.1.1 on 2019-01-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='category',
            field=models.CharField(choices=[('COMPUTER', 'computer'), ('IT', 'it'), ('ENTC', 'entc'), ('MECHANICAL', 'mechanical'), ('CIVIL', 'civil'), ('OTHER', 'other')], default='COMPUTER', max_length=100),
        ),
    ]
