# Generated by Django 2.1.1 on 2019-01-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0010_contactus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
