# Generated by Django 2.1.3 on 2018-11-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=5)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
