# Generated by Django 2.1.3 on 2018-11-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GandharvaWeb19', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
